---
- name: Disable consistent network device naming
  hosts: [nodes]
  become: true
  tasks:
  - name: 01. Add parameters to string
    lineinfile:
      name: /etc/default/grub
      regexp: '(GRUB_CMDLINE_LINUX=.*).*"'
      line: '\1 net.ifnames=0 biosdevname=0"'
      backrefs: yes
      state: present
  - name: 02. Update grub config
    cmd: grub2-mkconfig -o /boot/grub2/grub.cfg