---
- name: Set SElinux boolean for Anonymous FTP upload
  seboolean:
    name:  "{{ item }}"
    state: true
    persistent: yes
  loop: 
    - ftpd_anon_write
    - allow_ftpd_full_access

- name: Set SElinux file context
  sefcontext:
    target: "{{ item }}"
    setype: public_content_rw_t
    state: present
  loop: "{{ ftp_path }}" 
  notify: run restorecon